plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
exclude:
  - .github
  - .idea
  - .vscode
  - Gemfile
  - Gemfile.lock
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Rakefile
  - README.md
  - deploy_key
  - deploy_key.enc
  - deploy_key.pub
title: Ruby on Rails Indonesia
description: Framework aplikasi web yang mencakup semua yang diperlukan untuk membuat aplikasi web yang didukung database sesuai dengan pola Model-View-Controller (MVC).
image: https://avatars.githubusercontent.com/u/46654718
url: https://rails.id
lang: id_ID
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/46654718
repository_url: https://github.com/rails-id/rails-id.github.io
ga_tracking_id: UA-133301636-1
